export const FETCH_MY_POSTS = "FETCH_MY_POSTS";
export const FETCH_USER_POSTS = "FETCH_USER_POSTS";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const REQUEST_CONNECTION = "REQUEST_CONNECTION";
export const REMOVE_CONNECTION = "REMOVE_CONNECTION";
export const ACCEPT_CONNECTION = "ACCEPT_CONNECTION";
export const REJECT_CONNECTION = "REJECT_CONNECTION";
export const WITHDRAW_CONNECTION = "WITHDRAW_CONNECTION";

export const CREATE_ROOM = "CREATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const FETCH_ROOM = "FETCH_ROOM";
export const SEND_MESSAGE = "SEND_MESSAGE";

export const MY_DETAILS = "MY_DETAILS";
export const ALL_USER = "ALL_USER";

export const EDIT_DETAILS = "EDIT_DETAILS";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";

export const ADD_PROFILE_PIC = "ADD_PROFILE_PIC";
export const REMOVE_PROFILE_PIC = "REMOVE_PROFILE_PIC";
export const ADD_COVER_PIC = "ADD_COVER_PIC";
export const REMOVE_COVER_PIC = "REMOVE_COVER_PIC";

export const FETCH_SUB_POSTS = "FETCH_SUB_POSTS";
export const FETCH_A_POST = "FETCH_A_POST";
export const LIKE_A_POST = "LIKE_A_POST";
export const UNLIKE_A_POST = "UNLIKE_A_POST";
export const COMMENT_A_POST = "COMMENT_A_POST";
export const DELETE_A_COMMENT = "DELETE_A_COMMENT";
export const DELETE_A_POST = "DELETE_A_POST";
export const EDIT_A_POST = "EDIT_A_POST";
export const CREATE_A_POST = "CREATE_A_POST";

export const LOGIN_USER = "LOGIN_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const CLEAR_DATA = "CLEAR_DATA";
